"""Client for the Movie Review Analytics service API.

Thin HTTPS wrapper around the hosted vision / transcription / language / storage
endpoints.  Configure with environment variables:

    MOCK_BASE_URL   service base URL (from your dashboard)
    TEST_TOKEN      your session token (from signup)

Do not edit this file — it mirrors the hosted API contract.
"""

from __future__ import annotations

import os
from typing import Any

import httpx

BASE_URL = os.environ.get("MOCK_BASE_URL", "https://mock.moviereviewanalytics.dev")
TIMEOUT = float(os.environ.get("MOCK_TIMEOUT", "120"))


class Client:
    def __init__(self) -> None:
        self._http = httpx.Client(timeout=TIMEOUT)

    def _call(self, method: str, **params: Any) -> Any:
        resp = self._http.post(
            f"{BASE_URL}/v1/call",
            json={"method": method, "params": params},
            headers={
                "Authorization": f"Bearer {os.environ.get('TEST_TOKEN', '')}",
                "X-Attempt-Id": os.environ.get("ATTEMPT_ID", ""),
            },
        )
        resp.raise_for_status()
        return resp.json()

    # storage
    def blob_fetch(self, key: str) -> dict[str, Any]:
        return self._call("blob_fetch", key=key)

    def blob_put(self, key: str, data: Any) -> dict[str, Any]:
        return self._call("blob_put", key=key, data=data)

    # vision
    def vision_shot_detect(self, video_id: str, duration_s: float) -> list[dict[str, Any]]:
        return self._call("vision_shot_detect", video_id=video_id, duration_s=duration_s)

    def vision_frame_analyse(self, frame_ids: list[str]) -> dict[str, Any]:
        return self._call("vision_frame_analyse", frame_ids=frame_ids)

    def vision_logo_detect(self, video_id: str, duration_s: float) -> dict[str, Any]:
        return self._call("vision_logo_detect", video_id=video_id, duration_s=duration_s)

    def vision_explicit_detect(self, video_id: str, duration_s: float) -> dict[str, Any]:
        return self._call("vision_explicit_detect", video_id=video_id, duration_s=duration_s)

    def vision_text_detect(self, video_id: str, duration_s: float) -> dict[str, Any]:
        return self._call("vision_text_detect", video_id=video_id, duration_s=duration_s)

    def vision_face_detect(self, video_id: str, duration_s: float) -> dict[str, Any]:
        return self._call("vision_face_detect", video_id=video_id, duration_s=duration_s)

    # transcription
    def transcribe(self, audio_id: str, duration_s: float, enable_diarization: bool = True) -> dict[str, Any]:
        return self._call(
            "transcribe", audio_id=audio_id, duration_s=duration_s, enable_diarization=enable_diarization
        )

    # language
    def llm(self, prompt: str, *, model: str = "pro", output_schema: str | None = None) -> str:
        return self._call("llm", prompt=prompt, model=model, output_schema=output_schema)

    def llm_large(self, prompt: str, *, output_schema: str | None = None) -> str:
        return self.llm(prompt, model="pro", output_schema=output_schema)

    def llm_medium(self, prompt: str, *, output_schema: str | None = None) -> str:
        return self.llm(prompt, model="flash", output_schema=output_schema)

    def llm_small(self, prompt: str, *, output_schema: str | None = None) -> str:
        return self.llm(prompt, model="nano", output_schema=output_schema)


_default_client: Client | None = None


def get_client() -> Client:
    global _default_client
    if _default_client is None:
        _default_client = Client()
    return _default_client
